// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mythos/cosmosmod/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/x/auth/types"
	_ "github.com/cosmos/cosmos-sdk/x/bank/types"
	_ "github.com/cosmos/cosmos-sdk/x/gov/types/v1"
	types "github.com/cosmos/cosmos-sdk/x/slashing/types"
	_ "github.com/cosmos/cosmos-sdk/x/staking/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the cosmosmod module's genesis state.
type GenesisState struct {
	Staking      StakingGenesisState      `protobuf:"bytes,1,opt,name=staking,proto3" json:"staking"`
	Bank         BankGenesisState         `protobuf:"bytes,2,opt,name=bank,proto3" json:"bank"`
	Gov          GovGenesisState          `protobuf:"bytes,3,opt,name=gov,proto3" json:"gov"`
	Auth         AuthGenesisState         `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth"`
	Slashing     types.GenesisState       `protobuf:"bytes,5,opt,name=slashing,proto3" json:"slashing"`
	Distribution DistributionGenesisState `protobuf:"bytes,6,opt,name=distribution,proto3" json:"distribution"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a233361b8a57f32f, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetStaking() StakingGenesisState {
	if m != nil {
		return m.Staking
	}
	return StakingGenesisState{}
}

func (m *GenesisState) GetBank() BankGenesisState {
	if m != nil {
		return m.Bank
	}
	return BankGenesisState{}
}

func (m *GenesisState) GetGov() GovGenesisState {
	if m != nil {
		return m.Gov
	}
	return GovGenesisState{}
}

func (m *GenesisState) GetAuth() AuthGenesisState {
	if m != nil {
		return m.Auth
	}
	return AuthGenesisState{}
}

func (m *GenesisState) GetSlashing() types.GenesisState {
	if m != nil {
		return m.Slashing
	}
	return types.GenesisState{}
}

func (m *GenesisState) GetDistribution() DistributionGenesisState {
	if m != nil {
		return m.Distribution
	}
	return DistributionGenesisState{}
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "mythos.cosmosmod.v1.GenesisState")
}

func init() { proto.RegisterFile("mythos/cosmosmod/v1/genesis.proto", fileDescriptor_a233361b8a57f32f) }

var fileDescriptor_a233361b8a57f32f = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4e, 0xea, 0x40,
	0x14, 0x87, 0xdb, 0x0b, 0x97, 0x7b, 0x53, 0x59, 0x55, 0x17, 0x0d, 0x26, 0x55, 0x0c, 0x18, 0x5c,
	0x38, 0x13, 0x70, 0x6b, 0x62, 0x24, 0x26, 0xb8, 0x70, 0x25, 0x0b, 0x13, 0x37, 0x64, 0x0a, 0x93,
	0xe9, 0x04, 0xda, 0x21, 0x9d, 0xe9, 0x08, 0x6f, 0xe1, 0xf3, 0xf8, 0x04, 0x2c, 0x59, 0xba, 0x32,
	0x06, 0x5e, 0xc4, 0x4c, 0xff, 0x90, 0x82, 0x83, 0x31, 0x61, 0x41, 0xa6, 0xdf, 0xf7, 0x3b, 0x67,
	0xce, 0x1c, 0xab, 0x1e, 0xcc, 0x85, 0xcf, 0x38, 0x1c, 0x32, 0x1e, 0xa8, 0xdf, 0x08, 0xca, 0x36,
	0x24, 0x38, 0xc4, 0x9c, 0x72, 0x30, 0x8d, 0x98, 0x60, 0xf6, 0x61, 0x8a, 0x80, 0x0d, 0x02, 0x64,
	0xbb, 0x76, 0x44, 0x18, 0x61, 0xc9, 0x77, 0xa8, 0xfe, 0xa5, 0x68, 0xad, 0x91, 0x32, 0x90, 0x0b,
	0x34, 0xa6, 0x21, 0x81, 0xb2, 0xed, 0x61, 0x81, 0x76, 0x02, 0x6b, 0xf5, 0x8c, 0xf2, 0x50, 0x38,
	0xde, 0x83, 0x1c, 0x67, 0x08, 0x61, 0xf2, 0x5b, 0x43, 0x1b, 0x1f, 0xc5, 0xc2, 0xdf, 0xe3, 0x37,
	0xf3, 0x46, 0x26, 0x88, 0xfb, 0xfb, 0x3b, 0x39, 0xd7, 0xdd, 0x5e, 0xb5, 0x35, 0xd8, 0xe6, 0x2e,
	0x74, 0x5c, 0x76, 0xc9, 0x1d, 0xb4, 0xa9, 0x1d, 0x28, 0x93, 0x83, 0x5f, 0x54, 0x56, 0x17, 0xda,
	0xe1, 0x80, 0x8e, 0x1b, 0x51, 0x2e, 0x22, 0xea, 0xc5, 0x82, 0xb2, 0x70, 0x9b, 0x3f, 0x7b, 0x2b,
	0x59, 0xd5, 0x5e, 0x7a, 0xd2, 0x17, 0x48, 0x60, 0xfb, 0xde, 0xfa, 0x97, 0x35, 0xea, 0x98, 0xa7,
	0x66, 0xeb, 0xa0, 0xd3, 0x02, 0x9a, 0xf7, 0x04, 0xfd, 0x94, 0x29, 0xaa, 0xdd, 0xf2, 0xe2, 0xe3,
	0xc4, 0x78, 0xcc, 0x75, 0xfb, 0xc6, 0x2a, 0xab, 0xd1, 0x38, 0x7f, 0x92, 0x98, 0xa6, 0x36, 0xa6,
	0x8b, 0xc2, 0xb1, 0x26, 0x23, 0x11, 0xed, 0x6b, 0xab, 0x44, 0x98, 0x74, 0x4a, 0x89, 0xdf, 0xd0,
	0xfa, 0x3d, 0x26, 0x35, 0xba, 0xd2, 0x54, 0x79, 0x35, 0x1f, 0xa7, 0xfc, 0x43, 0xf9, 0xdb, 0x58,
	0xf8, 0xba, 0xf2, 0x4a, 0xb4, 0x7b, 0xd6, 0xff, 0x7c, 0x1d, 0x9c, 0xbf, 0x59, 0x48, 0x6a, 0x83,
	0xfc, 0x1c, 0x64, 0x6b, 0x02, 0x34, 0x21, 0x1b, 0xd9, 0x7e, 0xb2, 0xaa, 0xc5, 0x17, 0x70, 0x2a,
	0x49, 0xd8, 0xa5, 0xb6, 0xa3, 0xbb, 0x02, 0xa8, 0x09, 0xdd, 0x0a, 0xea, 0x3e, 0x2c, 0x56, 0xae,
	0xb9, 0x5c, 0xb9, 0xe6, 0xe7, 0xca, 0x35, 0x5f, 0xd7, 0xae, 0xb1, 0x5c, 0xbb, 0xc6, 0xfb, 0xda,
	0x35, 0x9e, 0x3b, 0x84, 0x0a, 0x3f, 0xf6, 0xc0, 0x90, 0x05, 0x70, 0xc2, 0x22, 0x3c, 0x42, 0x21,
	0x1a, 0xd2, 0x88, 0x0b, 0x8c, 0xe0, 0x0b, 0xe2, 0xc1, 0x0c, 0xce, 0x0a, 0x2b, 0x22, 0xe6, 0x53,
	0xcc, 0xbd, 0x4a, 0xb2, 0x11, 0x57, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x00, 0x31, 0x3e,
	0xe3, 0x03, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Distribution.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.Slashing.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.Auth.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.Gov.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Bank.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Staking.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Staking.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.Bank.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.Gov.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.Auth.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.Slashing.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.Distribution.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Staking", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Staking.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bank", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Bank.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gov", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Gov.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Auth", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Auth.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slashing", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Slashing.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Distribution", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Distribution.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
