# This workflow is useful if you want to automate the process of:
#
# a) Creating a new prelease when you push a new tag with a "v" prefix (version).
#
#    This type of prerelease is meant to be used for production: alpha, beta, rc, etc. types of releases.
#    After the prerelease is created, you need to make your changes on the release page at the relevant
#    Github page and publish your release.
#
# The workflow will run only if a tag with a "v" prefix is pushed.
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Mythos-Wazero Binary for Multiple Platforms
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/loredanacirstea*
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64
          - os: ubuntu-latest
            arch: arm64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

    - name: Set up environment variables
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          echo "GOOS=linux" >> $GITHUB_ENV
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          echo "GOOS=darwin" >> $GITHUB_ENV
        elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          echo "GOOS=windows" >> $GITHUB_ENV
        fi
        echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV
        echo "TAG_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      shell: bash

    - name: Set up binary path in environment
      run: |
        echo "BINARY_PATH=mythos-wz-${{ env.TAG_VERSION }}-${{ env.GOOS }}-${{ env.GOARCH }}" >> $GITHUB_ENV
      shell: bash

    - name: Build binary
      run: |
        echo "GOOS=$GOOS"
        echo "GOARCH=$GOARCH"
        echo "TAG_VERSION=$TAG_VERSION"
        echo "BINARY_PATH=$BINARY_PATH"

        cd mythos-wazero
        echo "cd mythos-wazero"
        pwd && ls -a
        make build-path
        echo "ls mythos-wazero/build"
        ls -R ./build
        cd .. && pwd

    - name: Compress binary folder
      run: |
        cd mythos-wazero/build
        echo "Compressing folder: ${{ env.BINARY_PATH }}"
        tar -czvf "${{ env.BINARY_PATH }}.tar.gz" "${{ env.BINARY_PATH }}"
        ls -a
        cd ../..

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.BINARY_PATH }}.tar.gz
        path: |
          ./mythos-wazero/build/${{ env.BINARY_PATH }}.tar.gz

  release:
    name: Release Binaries
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3

    - name: Display structure of downloaded files
      run: ls -R

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        prerelease: false
        draft: true

    - name: Upload Release Assets
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: |
          ./mythos-wz-*.tar.gz
        tag: ${{ github.ref_name }}
        overwrite: true
        file_glob: true
