name: Run Go WasmX Tests

on:
  push:
    branches:
      - main # Trigger on push to the "main" branch
  pull_request:
    branches:
      - main # Trigger on pull request to the "main" branch

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Set up CGO environment variables
        run: |
          echo "CGO_LDFLAGS='-Wl,-rpath,/usr/local/lib'" >> $GITHUB_ENV

      - name: Run tests
        run: |
          go test -v ./tests/wasmx
          go test -v ./wasmx/...
          go test -v ./wasmx-wasmedge/...
          go test -v ./wasmx-wazero/...
          go test -v ./mythos-wasmedge/...
          go test -v ./mythos-wazero/...

