name: Run Go Tests

on:
  push:
    branches:
      - main # Trigger on push to the "main" branch
  pull_request:
    branches:
      - main # Trigger on pull request to the "main" branch

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23 # Adjust to match your Go version

    # Step 3: Install WasmEdge
    - name: Install WasmEdge
      run: |
        curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.13.4
        echo "/usr/local/lib" >> /etc/ld.so.conf.d/wasmedge.conf
        ldconfig

    # Step 4: Install dependencies (optional)
    - name: Install dependencies
      run: |
        go mod tidy

    # Step 5: Set up environment variables for CGO
    - name: Set up CGO environment variables
      run: |
        echo "CGO_LDFLAGS='-Wl,-rpath,/usr/local/lib'" >> $GITHUB_ENV

    # Step 6: Run tests in each subpackage
    - name: Run tests
      run: |
        go test -v ./tests/wasmx
        go test -v ./wasmx/...
        go test -v ./wasmx-wasmedge/...
        go test -v ./wasmx-wazero/...
        go test -v ./mythos-wasmedge/...
        go test -v ./mythos-wazero/...

    # Optional: Save test results for analysis
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: '**/test-results/*.txt'
