name: Run Go WasmX Tests

on:
  push:
   branches:
     - main # Trigger on push to the "main" branch
  pull_request:
    branches:
      - main # Trigger on pull request to the "main" branch

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/loredanacirstea*
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

      #- name: Install WasmEdge
      #  run: curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.13.4

      #- name: Verify WasmEdge Installation
      #  run: |
      #    echo "WasmEdge directory: $HOME/.wasmedge"

      - name: Run tests
        #env:
        #  WASMEDGE_DIR: /home/runner/.wasmedge
        #  DYLD_LIBRARY_PATH: /home/runner/.wasmedge/lib
        #  LD_LIBRARY_PATH: /home/runner/.wasmedge/lib
        #  LIBRARY_PATH: /home/runner/.wasmedge/lib
        #  WASMEDGE_LIB_DIR: /home/runner/.wasmedge/lib
        #  C_INCLUDE_PATH: /home/runner/.wasmedge/include
        #  CPLUS_INCLUDE_PATH: /home/runner/.wasmedge/include
        #  CGO_LDFLAGS: -Wl,-rpath,/home/runner/.wasmedge/lib
        run: |
          go test -failfast=false -v ./wasmx/...
          go test -failfast=false -v ./wasmx-wazero/...
          go test -failfast=false -v ./mythos-wazero/...
          go test -failfast=false -timeout 4000s -v ./tests/wasmx -wasm-runtime=wazero
          go test -failfast=false -timeout 2000s -v ./tests/cosmosmod -wasm-runtime=wazero
          go test -failfast=false -timeout 4000s -v ./tests/network -wasm-runtime=wazero
          go test -failfast=false -timeout 2000s -v ./tests/vmsql -wasm-runtime=wazero
          go test -failfast=false -timeout 2000s -v ./tests/vmkv -wasm-runtime=wazero
          go test -failfast=false -timeout 2000s -v ./tests/vmhttp -wasm-runtime=wazero
          go test -failfast=false -timeout 2000s -v ./tests/vmemail -wasm-runtime=wazero
