name: Run Go WasmX Tests

on:
  push:
    branches:
      - main # Trigger on push to the "main" branch
  pull_request:
    branches:
      - main # Trigger on pull request to the "main" branch

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # This option enables checking out private dependencies
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Set env variables
        run: |
          echo "GOPRIVATE=github.com/loredanacirstea*" >> $GITHUB_ENV

      - name: Run tests
        run: |
          go test -v ./wasmx/...
          go test -v ./wasmx-wazero/...
          go test -v ./mythos-wazero/...
          go test -v -short ./tests/wasmx

